server:
  port: 8092

spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: system
    password: sia
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true   
login-app:
  messages:
    invalidCredentials: Your credentials are not valid!!
    success: You are successfully login into your account!!
  